<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PAT-R4P10" name="Default test" tests="1" failures="0" timestamp="5 Oct 2016 11:23:58 GMT" time="3.75" errors="0">
  <testcase name="@BeforeClass intialize" time="0.0" classname="com.db.test.DbTester">
    <failure type="org.apache.openejb.OpenEjbContainer$InvalidApplicationException" message="org.apache.openejb.config.ValidationFailedException: Module failed validation. AppModule(name=)">
      <![CDATA[org.apache.openejb.OpenEjbContainer$InvalidApplicationException: org.apache.openejb.config.ValidationFailedException: Module failed validation. AppModule(name=)
	at org.apache.openejb.OpenEjbContainer$Provider.createEJBContainer(OpenEjbContainer.java:291)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:56)
	at javax.ejb.embeddable.EJBContainer.createEJBContainer(EJBContainer.java:43)
	at com.db.test.DbTester.intialize(DbTester.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: org.apache.openejb.config.ValidationFailedException: Module failed validation. AppModule(name=)
	at org.apache.openejb.config.ReportValidationResults.deploy(ReportValidationResults.java:82)
	at org.apache.openejb.config.AppInfoBuilder.build(AppInfoBuilder.java:266)
	at org.apache.openejb.config.ConfigurationFactory.configureApplication(ConfigurationFactory.java:795)
	at org.apache.openejb.OpenEjbContainer$Provider.createEJBContainer(OpenEjbContainer.java:285)
	... 27 more
]]>
    </failure>
  </testcase> <!-- @BeforeClass intialize -->
  <testcase name="test2" time="0.001" classname="com.db.test.DbTester">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test -->
